# Generated by Django 2.2.1 on 2019-08-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('AutoId', models.AutoField(primary_key=True, serialize=False)),
                ('Id', models.CharField(default='', max_length=50)),
                ('Description', models.CharField(default='', max_length=50)),
                ('ActiveStatus', models.BooleanField(default=True)),
            ],
        ),
    ]
