# Generated by Django 2.2.1 on 2019-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factogridApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ActiveStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EquipmentProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propId', models.CharField(default='', max_length=50)),
                ('propDesc', models.CharField(default='', max_length=50)),
                ('propValue', models.CharField(default='', max_length=50)),
                ('propUOM', models.CharField(default='', max_length=50)),
                ('propAS', models.BooleanField(default=False)),
                ('equipId', models.ForeignKey(on_delete=True, to='factogridApp.Equipment')),
            ],
        ),
    ]
